# Generated by Django 4.1.6 on 2023-08-29 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner_app', '0001_initial'),
        ('triggers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='owner_app.owner')),
                ('triggers', models.ManyToManyField(to='triggers_app.triggers')),
            ],
        ),
    ]
