# Generated by Django 4.1.6 on 2023-08-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_app', '0002_alter_dog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='likes',
            field=models.ManyToManyField(blank=True, to='dog_app.dog'),
        ),
    ]
