# Generated by Django 4.1.6 on 2023-08-29 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
        ('dog_app', '0003_dog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='owner_app.owner'),
        ),
    ]
