# Generated by Django 4.1.6 on 2023-09-27 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('dog_app', '0004_alter_dog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.userprofile'),
        ),
    ]
