# Generated by Django 4.1.6 on 2023-09-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_app', '0005_alter_dog_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='owner',
        ),
    ]
