version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    ports:
      - "80:80"
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dogs_park_proj
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: