# Generated by Django 4.1.6 on 2023-08-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_park_name', models.CharField(max_length=255)),
                ('dogs', models.ManyToManyField(to='dog_app.dog')),
            ],
        ),
    ]
